# Generated by Django 2.2.5 on 2019-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=2)),
                ('zodic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('nick1', models.CharField(max_length=50)),
                ('nick2', models.CharField(max_length=50)),
                ('skils', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('music', models.CharField(max_length=50)),
                ('movie', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('actress', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('person', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
