# Generated by Django 2.2.5 on 2019-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
