# Generated by Django 2.2.5 on 2019-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0002_auto_20190920_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='actor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='actress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='food',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='movie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='music',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='nick1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='nick2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='person',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='skils',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='sport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slam',
            name='zodic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
