# Generated by Django 2.2.5 on 2019-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0003_auto_20190920_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
