# Generated by Django 2.2.5 on 2019-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0005_auto_20190920_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slam',
            name='img',
        ),
    ]
