# Generated by Django 2.2.5 on 2019-09-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0007_slam_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slam',
            name='photo',
        ),
    ]
