# Generated by Django 2.2.5 on 2019-09-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0009_auto_20190922_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
