# Generated by Django 2.2.5 on 2019-09-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0010_auto_20190922_0316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
