# Generated by Django 2.2.5 on 2019-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0011_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='slam',
            name='photo',
            field=models.FileField(default='J', upload_to=''),
        ),
    ]
