# Generated by Django 2.2.5 on 2019-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0012_slam_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
