# Generated by Django 2.2.5 on 2019-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myslambook', '0015_auto_20190924_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
